package Products.View;

import Products.Model.Entity.Product;
import Stock.Model.Entity.Stock;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class MainView extends javax.swing.JFrame {

    public ProductView productView;
    public StockProductsView stockPView;

    /**
     * Creates new form ProductsView
     */
    public MainView() {
        initComponents();
        setup();
    }

    private void setup() {
        productView = new ProductView();
        stockPView = new StockProductsView();
        productView.setSize(800, 600);
        stockPView.setSize(800, 600);
        this.stockPView.setLocation(0, 0);
        this.productView.setLocation(0, 0);
         this.container.add(this.stockPView, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        menuProducts = new javax.swing.JMenuBar();
        mViewStock = new javax.swing.JMenu();
        miViewStock = new javax.swing.JMenuItem();
        mAddProduct = new javax.swing.JMenu();
        miAddProduct = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        mViewStock.setText("Stock");

        miViewStock.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        miViewStock.setText("Ver Stock");
        miViewStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miViewStockActionPerformed(evt);
            }
        });
        mViewStock.add(miViewStock);

        menuProducts.add(mViewStock);

        mAddProduct.setText("Producto");

        miAddProduct.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        miAddProduct.setText("Agregar producto");
        miAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAddProductActionPerformed(evt);
            }
        });
        mAddProduct.add(miAddProduct);

        menuProducts.add(mAddProduct);

        setJMenuBar(menuProducts);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miViewStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miViewStockActionPerformed

        this.container.removeAll();
        this.container.add(this.stockPView, BorderLayout.CENTER);
        this.container.revalidate();
        this.container.repaint();
    }//GEN-LAST:event_miViewStockActionPerformed

    private void miAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAddProductActionPerformed

        this.container.removeAll();
        this.container.add(this.productView, BorderLayout.CENTER);
        this.container.revalidate();
        this.container.repaint();
    }//GEN-LAST:event_miAddProductActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel container;
    private javax.swing.JMenu mAddProduct;
    public javax.swing.JMenu mViewStock;
    private javax.swing.JMenuBar menuProducts;
    private javax.swing.JMenuItem miAddProduct;
    private javax.swing.JMenuItem miViewStock;
    // End of variables declaration//GEN-END:variables
}
